# Path to your oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh
export DOTFILES=$HOME/dotfiles

# Set to the name theme to load.
# Look in ~/.oh-my-zsh/themes/
export ZSH_THEME="robbyrussell"

# Set to this to use case-sensitive completion
# export CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# export DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# export DISABLE_LS_COLORS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git osx brew git-flow vagrant)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
export PATH=:$HOME/bin:/usr/local/share/python:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin:/usr/local/share/npm/bin:/usr/local/sbin:/usr/local/Cellar/ruby/1.9.2-p136/bin:$PATH

source $DOTFILES/postgresql/aliases.zsh
source $DOTFILES/couchdb/aliases.zsh
source $DOTFILES/memcached/aliases.zsh
#source $DOTFILES/python/virtualenv.zsh
source $DOTFILES/scm_breeze/init.zsh
source $DOTFILES/aliases/init.zsh

export LESSCHARSET=utf-8
export LANG=is_IS.UTF-8
export OUTPUT_CHARSET=utf-8
export LC_MESSAGES=c
export LC_CTYPE=en_US.UTF-8
export ERL_LIBS=~/.erlibs
export EDITOR=emacs
setopt NO_beep

alias vi='vim'
alias reload='source ~/.zshrc'
alias mv='mv -i'
alias tmux='tmux -u'
alias mutt='cd ~/Desktop && mutt'